function saved = savedInit (robot,spiral,nbSamples)
    %UNTITLED2 Summary of this function goes here
    %   Detailed explanation goes here
    
    saved = struct('state',zeros(3, nbSamples),...
               'control',zeros(2, nbSamples),...
               'distance',zeros(1, nbSamples),...
               'distanceRef',zeros(1, nbSamples),...
               'spiral',zeros(2, nbSamples),...
               'alpha',zeros(1, nbSamples-1),...
               'error',zeros(2,nbSamples-1)...
               );
           
saved.state(:,1) = [robot.x;robot.y;robot.theta];
saved.control(:,1) = [robot.v;robot.w];
saved.distance(:,1) = robot.distance;
saved.distanceRef(1,1) = spiral.distance;
saved.spiral(:,1) = [spiral.x,spiral.y]';

end

